import { useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { motion } from 'framer-motion';
import I from '../components/icons';
const HiOutlineLightBulb = I.Bulb;
const HiOutlineThermometer = I.Thermo;
const HiOutlineCloud = I.Cloud;
const HiOutlineCalendar = I.Calendar;
const HiOutlineExclamationTriangle = I.Exclamation;
const HiOutlineHeart = I.Heart;
const HiOutlineSparkles = I.Sparkles;
const HiOutlineArrowRight = I.ArrowRight;
const HiOutlineUpload = I.Upload;
const HiOutlineCheckCircle = I.CheckCircle;
const HiOutlineClock = I.Clock;
const HiOutlineInformationCircle = I.InfoCircle;
import Button from '../components/ui/Button';
import Badge, { StatusBadge } from '../components/ui/Badge';
import { Skeleton, CardSkeleton } from '../components/ui/Skeleton';
import { EmptyState } from '../components/ui/EmptyState';
import { GaugeChart, CircularProgress } from '../components/ui/Progress';
import { recommendationService } from '../services/api';
import { useLazyApi } from '../hooks/useApi';
import { getStatusColor, cn } from '../utils/helpers';

const Recommendations = () => {
  const navigate = useNavigate();
  const { data, load, loading } = useLazyApi(recommendationService.getAll);

  useEffect(() => { load(); }, []);

  const recommendations = data || [];

  return (
    <div className="space-y-8">
      {/* Header */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        className="relative overflow-hidden rounded-[2rem] bg-gradient-to-r from-primary-600 via-secondary-600 to-accent-500 p-8 md:p-10 shadow-xl shadow-secondary-500/25"
      >
        <div className="absolute inset-0 bg-grid opacity-20" />
        <div className="absolute -top-20 -right-20 w-80 h-80 bg-white/10 rounded-full blur-3xl" />

        <div className="relative flex flex-col md:flex-row md:items-center md:justify-between gap-6">
          <div className="max-w-2xl">
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-white/20 backdrop-blur-sm border border-white/20 mb-4">
              <HiOutlineLightBulb className="w-4 h-4 text-yellow-200" />
              <span className="text-xs font-bold text-white/90">AI-Powered Insights</span>
            </div>
            <h1 className="text-3xl md:text-4xl lg:text-5xl font-black text-white mb-3 leading-tight">
              Smart Recommendations
            </h1>
            <p className="text-white/85 text-base md:text-lg leading-relaxed">
              Personalized storage advice, health warnings, and nutrition tips generated by FreshNet AI based on your analyzed items.
            </p>
          </div>
          <div className="flex flex-col sm:flex-row gap-3 shrink-0">
            <div className="flex items-center gap-3 px-5 py-4 rounded-2xl bg-white/15 backdrop-blur-md border border-white/20">
              <div className="text-4xl">💡</div>
              <div>
                <p className="text-3xl font-black text-white leading-none">{recommendations.length}</p>
                <p className="text-[11px] font-bold text-white/70 uppercase tracking-wider">Active Tips</p>
              </div>
            </div>
            <Button
              variant="ghost"
              className="!bg-white !text-primary-700 hover:!bg-white/90 !shadow-lg"
              icon={<HiOutlineUpload className="w-5 h-5" />}
              onClick={() => navigate('/upload')}
            >
              Analyze Item
            </Button>
          </div>
        </div>
      </motion.div>

      {/* Legend */}
      <div className="card p-5 md:p-6">
        <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
          <div className="flex items-center gap-3">
            <HiOutlineInformationCircle className="w-5 h-5 text-secondary-500 shrink-0" />
            <p className="text-sm text-slate-600 dark:text-slate-400 font-medium">
              Cards are organized by freshness status. <b className="text-slate-800 dark:text-slate-200">Green</b> items are in great shape, <b className="text-slate-800 dark:text-slate-200">Orange</b> need attention soon, <b className="text-slate-800 dark:text-slate-200">Red</b> need immediate action.
            </p>
          </div>
          <div className="flex flex-wrap items-center gap-4">
            {[
              { s: 'fresh', l: 'Fresh & Safe' },
              { s: 'moderate', l: 'Moderate Risk' },
              { s: 'spoiled', l: 'Action Required' },
            ].map(t => {
              const c = getStatusColor(t.s);
              return (
                <div key={t.s} className="flex items-center gap-2">
                  <span className={`w-3 h-3 rounded-full ${c.bg} shadow-sm`} />
                  <span className="text-xs font-bold text-slate-600 dark:text-slate-400">{t.l}</span>
                </div>
              );
            })}
          </div>
        </div>
      </div>

      {/* Cards Grid */}
      {loading ? (
        <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-6">
          {Array.from({ length: 6 }).map((_, i) => <CardSkeleton key={i} lines={4} />)}
        </div>
      ) : recommendations.length === 0 ? (
        <EmptyState
          icon="data"
          title="No recommendations yet"
          description="Start analyzing food items to receive personalized storage recommendations and nutrition tips."
          action
          actionLabel="Analyze First Item"
          onAction={() => navigate('/upload')}
        />
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-6">
          {recommendations.map((r, i) => {
            const c = getStatusColor(r.status);
            return (
              <motion.article
                key={r.id}
                initial={{ opacity: 0, y: 25, scale: 0.98 }}
                animate={{ opacity: 1, y: 0, scale: 1 }}
                transition={{ delay: i * 0.06, type: 'spring', damping: 22 }}
                whileHover={{ y: -6, scale: 1.01 }}
                className={cn(
                  'card overflow-hidden relative group',
                  r.status === 'spoiled' && 'ring-2 ring-danger-500/20'
                )}
              >
                {/* Status bar */}
                <div className={cn('absolute top-0 left-0 right-0 h-1.5 bg-gradient-to-r', c.gradient)} />

                {/* Image */}
                <div className="relative aspect-[16/9] overflow-hidden">
                  <img
                    src={r.image}
                    alt={r.food}
                    className="w-full h-full object-cover transition-transform duration-500 group-hover:scale-110"
                    loading="lazy"
                  />
                  <div className="absolute inset-0 bg-gradient-to-t from-black/70 via-black/10 to-transparent" />

                  <div className="absolute top-4 right-4">
                    <StatusBadge status={r.status}>
                      {r.status?.charAt(0).toUpperCase() + r.status?.slice(1)}
                    </StatusBadge>
                  </div>

                  <div className="absolute bottom-4 left-4 right-4 flex items-end justify-between gap-4">
                    <div>
                      <p className="text-white/70 text-[10px] font-bold uppercase tracking-wider mb-1">Recommended</p>
                      <h3 className="text-2xl md:text-3xl font-black text-white drop-shadow-lg leading-none">
                        {r.food}
                      </h3>
                    </div>
                    <CircularProgress
                      value={r.freshness}
                      size={64}
                      strokeWidth={5}
                      color={c.hex}
                    />
                  </div>
                </div>

                <div className="p-6 space-y-5">
                  {/* Gauge */}
                  <div className="flex justify-center -mt-2 mb-2">
                    <GaugeChart
                      value={r.freshness}
                      label="Freshness"
                      size={180}
                    />
                  </div>

                  {/* Grid of small stats */}
                  <div className="grid grid-cols-3 gap-3">
                    {[
                      { i: HiOutlineThermometer, l: 'Temp', v: `${r.recommendedTemp}°C`, tc: 'text-accent-600 dark:text-accent-400' },
                      { i: HiOutlineCloud, l: 'Humidity', v: `${r.recommendedHumidity}%`, tc: 'text-secondary-600 dark:text-secondary-400' },
                      { i: HiOutlineCalendar, l: 'Eat Within', v: r.consumeWithin === 0 ? 'Now' : `${r.consumeWithin}d`, tc: 'text-primary-600 dark:text-primary-400' },
                    ].map((s, si) => (
                      <div key={si} className="p-3 rounded-2xl bg-slate-50 dark:bg-slate-700/50 text-center">
                        <s.i className={cn('w-4 h-4 mx-auto mb-1.5', s.tc)} />
                        <p className="text-[9px] font-bold text-slate-400 dark:text-slate-500 uppercase tracking-wider">{s.l}</p>
                        <p className="text-sm font-black text-slate-800 dark:text-white leading-none">{s.v}</p>
                      </div>
                    ))}
                  </div>

                  {/* Storage Advice */}
                  <div className={cn('p-4 rounded-2xl', c.bgLight)}>
                    <div className="flex items-start gap-3">
                      <div className={cn('w-9 h-9 rounded-xl shrink-0 flex items-center justify-center', c.bg, 'text-white')}>
                        <HiOutlineCheckCircle className="w-4.5 h-4.5" />
                      </div>
                      <div>
                        <p className="text-[10px] font-bold uppercase tracking-wider mb-1 text-slate-500 dark:text-slate-400">Storage Advice</p>
                        <p className={cn('text-sm font-semibold leading-relaxed', c.text)}>
                          {r.storageAdvice}
                        </p>
                      </div>
                    </div>
                  </div>

                  {/* Health Warning */}
                  <div className={cn(
                    'p-4 rounded-2xl border',
                    r.status === 'spoiled'
                      ? 'bg-danger-50 dark:bg-danger-500/10 border-danger-200 dark:border-danger-500/30'
                      : r.status === 'moderate'
                      ? 'bg-accent-50 dark:bg-accent-500/10 border-accent-200 dark:border-accent-500/30'
                      : 'bg-success-50 dark:bg-success-500/10 border-success-200 dark:border-success-500/30'
                  )}>
                    <div className="flex items-start gap-3">
                      <div className={cn(
                        'w-9 h-9 rounded-xl shrink-0 flex items-center justify-center text-white',
                        r.status === 'spoiled' ? 'bg-danger-500' : r.status === 'moderate' ? 'bg-accent-500' : 'bg-success-500'
                      )}>
                        {r.status === 'spoiled' ? <HiOutlineExclamationTriangle className="w-4.5 h-4.5" /> : <HiOutlineHeart className="w-4.5 h-4.5" />}
                      </div>
                      <div>
                        <p className="text-[10px] font-bold uppercase tracking-wider mb-1 text-slate-500 dark:text-slate-400">Health Warning</p>
                        <p className={cn(
                          'text-sm font-semibold leading-relaxed',
                          r.status === 'spoiled' ? 'text-danger-700 dark:text-danger-400' :
                          r.status === 'moderate' ? 'text-accent-700 dark:text-accent-400' : 'text-success-700 dark:text-success-400'
                        )}>
                          {r.healthWarning}
                        </p>
                      </div>
                    </div>
                  </div>

                  {/* Nutrition */}
                  <div>
                    <div className="flex items-center gap-2 mb-2.5">
                      <HiOutlineHeart className="w-4 h-4 text-primary-500" />
                      <span className="text-[11px] font-bold uppercase tracking-wider text-slate-500 dark:text-slate-400">Nutrition Tip</span>
                    </div>
                    <p className="text-sm text-slate-600 dark:text-slate-400 leading-relaxed">
                      {r.nutritionTips}
                    </p>
                  </div>

                  {/* AI Suggestion */}
                  <div className="p-4 rounded-2xl bg-gradient-to-br from-secondary-500/5 via-primary-500/5 to-accent-500/5 border border-slate-200 dark:border-slate-700/50">
                    <div className="flex items-start gap-3">
                      <div className="w-9 h-9 rounded-xl shrink-0 bg-gradient-to-br from-secondary-500 to-primary-500 text-white flex items-center justify-center shadow-lg shadow-secondary-500/30">
                        <HiOutlineSparkles className="w-4.5 h-4.5" />
                      </div>
                      <div>
                        <p className="text-[10px] font-bold uppercase tracking-wider mb-1 text-slate-500 dark:text-slate-400">AI Suggestion</p>
                        <p className="text-sm font-semibold text-slate-700 dark:text-slate-300 leading-relaxed">
                          {r.aiSuggestions}
                        </p>
                      </div>
                    </div>
                  </div>

                  <div className="pt-4 border-t border-slate-100 dark:border-slate-700/50">
                    <Button
                      variant="primary"
                      fullWidth
                      icon={<HiOutlineArrowRight className="w-4 h-4" />}
                      iconPosition="right"
                      onClick={() => navigate(`/prediction?id=${r.id}`)}
                    >
                      View Full Analysis
                    </Button>
                  </div>
                </div>
              </motion.article>
            );
          })}
        </div>
      )}
    </div>
  );
};

export default Recommendations;
